### ISSUE TITLE
モデル作成 、 シードデータの作成

### ISSUE THREAD

**Issue by Hajiii88** [kakuko-deluxe/mofullo#1]
##モデル作成
 
以下の内容でTaskモデルを作成してください！！

カラム名 | データ型 | 備考
-- | -- | --
title | string | タスクのタイトル
body | text | タスクの本文
dua_date | date | タスクの期日

##シードデータ作成

以下の内容でTaskモデルに対する、シードデータを作成してください！

title | body | dua_date
-- | -- | --
"課題を提出する" | 現在取り組んでいる Rails アプリの課題を先生に提出する。\n 提出方法は Github にプッシュ後、プッシュしたリポジトリの URL を連絡する。 | "2019-12-30"
"高橋さんに連絡する" | "見積もりの件で金額を下げてもらうために交渉する。\n 駄目だった場合は直接会って土下座をする。" | "2019-8-30"
"ゴミを出す" | "月曜日は燃えないゴミの日なので忘れず出す" | "2019-9-1"

**Comment by noopy0415** [comment]
@Hajiii88 
マークダウンは#の後に空白を入れないと有効にならないです！
作成時にPreviewタブで確認出来ますので時間があったらやってみてください！

**Comment by Hajiii88** [comment]
小原さん 
ありがとう御座います！！
試してみます。
